name: vetjirani_flutter
description: A Flutter app to connect Kenyan farmers with licensed veterinarians for livestock healthcare.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.0.7
  firebase_messaging: ^14.3.0

  # Google Sign-In
  google_sign_in: ^6.1.0

  # State management
  provider: ^6.0.5

  # UI and utilities
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Video call and chat (placeholder packages)
  flutter_webrtc: ^0.9.22
  flutter_chat_ui: ^1.5.6
  flutter_chat_types: ^3.4.4

  # Location services
  geolocator: ^9.0.2
  permission_handler: ^10.4.0

  # Placeholder for M-Pesa payment integration
  http: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/offline_content/
